ALTER TABLE Products
ALTER COLUMN ProductID int IDENTITY(1,1) PRIMARY KEY;
DBCC CHECKIDENT ('Products', RESEED, 0);

ALTER TABLE Sales
ALTER COLUMN SaleID int identity(1,1) PRIMARY KEY;
DBCC CHECKIDENT ('Sales', RESEED, 0);

SELECT * FROM SALES